/* ------------------------------------------------------------------
   Module + hero artwork, generated by Pollinations AI.

   We store *prompts and seeds* rather than committing binary files, and
   build deterministic Pollinations image URLs at module-load time. A
   fixed seed per image keeps it stable across renders and builds, while
   the repo stays lean and the art is always regenerable by editing a
   prompt. Images are served remotely (image.pollinations.ai is allowed
   in next.config.ts `images.remotePatterns` and by the CSP img-src),
   so no build-time fetch is required.

   A shared STYLE suffix pins the palette to the pack theme (deep navy
   #0a2540, teal #0a6e8a / #1aa899) so every tile feels like one set.
------------------------------------------------------------------ */

import type { Section } from "./_types";

const STYLE =
  "isometric flat vector illustration, deep navy blue and teal colour palette, clean minimal corporate style, soft studio lighting, plain off-white background, no text, no words, no letters";

/** Build a deterministic Pollinations image URL for a prompt + seed. */
export function pollinationsUrl(
  prompt: string,
  seed: number,
  width = 480,
  height = 480
): string {
  const full = `${prompt}, ${STYLE}`;
  return (
    `https://image.pollinations.ai/prompt/${encodeURIComponent(full)}` +
    `?width=${width}&height=${height}&seed=${seed}&nologo=true&model=flux`
  );
}

interface ModuleArt {
  prompt: string;
  seed: number;
}

/** One on-theme prompt per module (keyed by Section.id). */
const MODULE_ART: Record<string, ModuleArt> = {
  "m01-foundations": {
    prompt:
      "a pristine modular building core with protected extension wings attached by clean standardised connectors",
    seed: 101,
  },
  "m02-hana-readiness": {
    prompt:
      "a glowing in-memory columnar database, bright vertical data columns, speed and light",
    seed: 102,
  },
  "m03-language": {
    prompt:
      "modern code refactoring, an old tangled scroll transforming into clean tidy building blocks",
    seed: 103,
  },
  "m04-abap-cloud": {
    prompt:
      "a layered cloud application stack with a clean REST service binding, floating service tiles",
    seed: 104,
  },
  "m05-released-apis": {
    prompt:
      "two systems connecting through a stable certified plug-and-socket API contract, secure handshake",
    seed: 105,
  },
  "m06-cds-amdp": {
    prompt:
      "a descending ladder of database query layers pushing computation down to the data engine",
    seed: 106,
  },
  "m07-performance": {
    prompt:
      "a performance speed gauge beside an optimized SQL execution plan flowchart, fast and efficient",
    seed: 107,
  },
  "m08-atc-migration": {
    prompt:
      "an automated code-quality inspection gate with a green checklist and a passing pipeline",
    seed: 108,
  },
  "m09-tools": {
    prompt:
      "a neat developer toolbox of polished utilities and instruments laid out on a workbench",
    seed: 109,
  },
  "m10-gotchas": {
    prompt:
      "hidden pitfalls and caution markers concealed inside an otherwise tidy machine, warning signs",
    seed: 110,
  },
  "m11-did-you-know": {
    prompt:
      "a bright lightbulb of discovery surrounded by small hidden gears and clever shortcuts",
    seed: 111,
  },
  "m12-recipes": {
    prompt:
      "a step-by-step recipe card with numbered procedure steps, a how-to cookbook for engineers",
    seed: 112,
  },
  "m13-capstones": {
    prompt:
      "an architect's blueprint leading up to a mountain summit flag, a culminating capstone project",
    seed: 113,
  },
  "m14-delivery": {
    prompt:
      "a collaborative project-management kanban and timeline board, teams coordinating across lanes",
    seed: 114,
  },
  "b01-management": {
    prompt:
      "a leadership dashboard of KPI charts and a downward-trending burndown line in a calm boardroom",
    seed: 115,
  },
  "b02-key-users": {
    prompt:
      "a business key user configuring app tiles with simple in-app no-code controls, friendly",
    seed: 116,
  },
  "b03-orientation": {
    prompt:
      "a clear orientation map with friendly signposts and a plain-language welcome route",
    seed: 117,
  },
};

/** Course landing hero (16:9). */
export const HERO_PROMPT =
  "a confident SAP ABAP developer modernizing a glowing protected software core, custom extensions orbiting safely around the stable centre, upgrade-ready";
export const HERO_SEED = 700;

export function moduleImageUrl(sectionId: string): string | undefined {
  const art = MODULE_ART[Object.hasOwn(MODULE_ART, sectionId) ? sectionId : ""];
  return art ? pollinationsUrl(art.prompt, art.seed) : undefined;
}

/**
 * Attach generated thumbnails to sections without mutating the source
 * module objects. A section that already carries an `iconImagePath`
 * keeps it; one with no mapped art is returned unchanged.
 */
export function withModuleImages(sections: Section[]): Section[] {
  return sections.map((s) => {
    if (s.iconImagePath) return s;
    const url = moduleImageUrl(s.id);
    return url ? { ...s, iconImagePath: url } : s;
  });
}
